# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # mlpack and anaconda docker image
      # previously circleci/python:3.6.1
      - image: davidinouye/destructive-deep-learning
      #  - image: davidinouye/research
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v0-1-0-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v0-1-0-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            # Needed to install POT correctly below
            pip install setuptools
            pip install Cython
            pip install numpy
            # Currently required by ddl package including for testing
            pip install pypandoc
            pip install pytest
            pip install pytest-cov
            pip install codecov
            pip install nose
            pip install pot
            pip install pandas
            pip install scikit-learn

      - save_cache:
          paths:
            - ./venv
          key: v0-1-0-dependencies-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
          - data-mnist-{{ checksum "scripts/maf_data.py" }}
          # fallback to using the latest cache if no exact match is found
          - data-mnist-

      - run:
          name: get mnist data
          command: |
            . venv/bin/activate
            # calls setup.py and downloads necessary packages if needed
            # Should be roughly equivalent to the following command
            # python setup.py install
            make data/mnist

      - save_cache:
          paths:
            - ./data
          key: data-mnist-{{ checksum "scripts/maf_data.py" }}

      - restore_cache:
          keys:
          - mlpack-1-{{ checksum "ddl/externals/mlpack/setup.py" }}-{{ checksum "ddl/externals/mlpack/_det.pyx" }}
          - mlpack-1-{{ checksum "ddl/externals/mlpack/setup.py" }}
          - mlpack-1-

      - run:
          name: install ddl
          command: |
            . venv/bin/activate
            # calls setup.py and downloads necessary packages if needed
            # Should be roughly equivalent to the following command
            # python setup.py install
            pip install --verbose .[test]

      - save_cache:
          paths:
            - ./ddl/externals/mlpack/mlpack-mlpack-3.0.2
          key: mlpack-1-{{ checksum "ddl/externals/mlpack/setup.py" }}-{{ checksum "ddl/externals/mlpack/_det.pyx" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
